# Keep the OS C library and GPU driver/loader dynamic. GGML_STATIC enables
# global -static, which is unsuitable for these driver-backed executables.
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(GGML_STATIC OFF CACHE BOOL "" FORCE)
set(GGML_BACKEND_DL OFF CACHE BOOL "" FORCE)
set(GGML_NATIVE OFF CACHE BOOL "" FORCE)
set(GGML_OPENMP OFF CACHE BOOL "" FORCE)
set(GGML_CUDA_NCCL OFF CACHE BOOL "" FORCE)
set(CMAKE_SKIP_RPATH ON)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
if(MSVC)
  add_compile_options($<$<COMPILE_LANGUAGE:C,CXX>:/utf-8>)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  add_link_options(-static-libgcc -static-libstdc++)
endif()

macro(laya_portable_cuda)
  set(laya_cuda_libraries CUDA::cudart_static CUDA::cublas CUDA::cublasLt)
  if(NOT WIN32)
    set(laya_cuda_libraries CUDA::cudart_static CUDA::cublas_static CUDA::cublasLt_static)
  endif()
  # Replace dependency target references as well as our own custom-kernel links.
  foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
    get_target_property(libraries ggml-cuda ${property})
    if(libraries)
      string(REPLACE "CUDA::cudart" "CUDA::cudart_static" libraries "${libraries}")
      if(NOT WIN32)
        string(REPLACE "CUDA::cublasLt" "CUDA::cublasLt_static" libraries "${libraries}")
        string(REPLACE "CUDA::cublas;" "CUDA::cublas_static;" libraries "${libraries}")
        string(REPLACE "CUDA::cublas>" "CUDA::cublas_static>" libraries "${libraries}")
        string(REGEX REPLACE "CUDA::cublas$" "CUDA::cublas_static" libraries "${libraries}")
      endif()
      set_property(TARGET ggml-cuda PROPERTY ${property} "${libraries}")
    endif()
  endforeach()
  set(CMAKE_CUDA_RUNTIME_LIBRARY Static)
endmacro()
